Models/DB/Ideas_De_Negocio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4MVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ideas_De_Negocio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ideas_De_Negocio()
        {
            this.Departamentos_Idea = new HashSet<Departamentos_Idea>();
            this.Integrantes = new HashSet<Integrantes>();
        }
    
        public int ID_Idea { get; set; }
        public string Nombre { get; set; }
        public int ID_Impacto { get; set; }
        public decimal Valor_Inversion { get; set; }
        public decimal Valor_Inversion_Infraestructura { get; set; }
        public decimal Total_Ingresos { get; set; }
        public int ID_Herramienta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamentos_Idea> Departamentos_Idea { get; set; }
        public virtual Herramientas4RI Herramientas4RI { get; set; }
        public virtual Impactos Impactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Integrantes> Integrantes { get; set; }
    }
}

Models/ViewModels/IdeasDeNegocioViewModels.cs
using ProyectoAula4MVC.Models.DB;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace ProyectoAula4MVC.Models.ViewModels
{
    

    public class RegistroIdeaViewModel
    {
        [Required]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Impacto")]
        public string Impacto { get; set; }


        [Required]
        [Display(Name = "Valor de inversion")]
        [Range(0, 9999999999, ErrorMessage = "La cantidad no puede ser negativa.")]
        public decimal ValorInversion { get; set; }



        [Required]
        [Display(Name = "Total de ingresos")]
        [Range(0, 9999999999, ErrorMessage = "La cantidad no puede ser negativa.")]
        public decimal TotalIngresos { get; set; }



        [Required]
        [Display(Name = "Valor de inversion en infraestructura")]
        [Range(0, 9999999999, ErrorMessage = "La cantidad no puede ser negativa.")]
        public decimal ValorInversionInfraestructura { get; set; }



        [Required]
        [Display(Name = "Herramienta de la 4 R.I")]
        public string Herramienta4RI { get; set; }

        [Required]
        [Display(Name = "Departamentos beneficiados")]
        public List<string> Departamentos { get; set; }
    }

    public class DetallesIdeaViewModel
    {

        [Display(Name = "Idea de Negocio")]
        public Ideas_De_Negocio Idea { get; set; }


        [Display(Name = "Departamentos beneficiados")]
        public List<Departamentos_Idea> Departamentos { get; set; }


    }

    public class EditarIdeaViewModel 
    {
        [Required]
        [Display(Name = "Id idea")]
        public int IdIdea { get; set; }


        [Required]
        [Display(Name = "Valor de inversion")] 
        [Range(0, 9999999999, ErrorMessage = "La cantidad no puede ser negativa.")]
        public decimal ValorInversion { get; set; }



        [Required]
        [Display(Name = "Total de ingresos")]
        [Range(0, 9999999999, ErrorMessage = "La cantidad no puede ser negativa.")]
        public decimal TotalIngresos { get; set; }


        [Required]
        [Display(Name = "Integrantes")]
        public List<IntegranteViewModel> Integrantes { get; set; }
    }
    public class IntegranteViewModel
    {

        [Required]
        [Display(Name = "NumId")]
        public int NumId { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Apellidos")]
        public string Apellidos { get; set; }

        [Required]
        [Display(Name = "Rol")]
        public string Rol { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Debe ingresar un correo electrónico válido.")]
        [Display(Name = "Correo electronico")]
        public string Email { get; set; }


    }

    public class EstadisticasViewModel 
    {
        public List<DetallesIdeaViewModel> ideasMas3Deptos { get; set; }
        public List<Ideas_De_Negocio> ideasMayorRentabilidad { get; set; }
        public List<Ideas_De_Negocio> ideasUsanDesarrolloSostenible { get; set; }
        public List<Ideas_De_Negocio> ideasRentabilidadMayorPromedio { get; set; }
        public List<Ideas_De_Negocio> ideasUsanTerritoriosOTransicion { get; set; }
        public DetallesIdeaViewModel ideaMayorDeptos { get; set; } 
        public Ideas_De_Negocio ideaMayorTotalIngresos { get; set; }
        public Ideas_De_Negocio ideaMayorInversionInfraestructura { get; set; }
        public decimal sumaTotalInversiones { get; set; }
        public decimal sumaTotalIngresos { get; set; }
        public int totalIdeasUsanIA { get; set; }

        public EstadisticasViewModel(List<DetallesIdeaViewModel> ideasMas3Deptos, List<Ideas_De_Negocio> ideasMayorRentabilidad, List<Ideas_De_Negocio> ideasUsanDesarrolloSostenible,
            List<Ideas_De_Negocio> ideasRentabilidadMayorPromedio, List<Ideas_De_Negocio> ideasUsanTerritoriosOTransicion, DetallesIdeaViewModel ideaMayorDeptos,
            Ideas_De_Negocio ideaMayorTotalIngresos, Ideas_De_Negocio ideaMayorInversionInfraestructura, decimal sumaTotalInversiones, decimal sumaTotalIngresos,
            int totalIdeasUsanIA)
        {
            this.ideasMas3Deptos = ideasMas3Deptos;
            this.ideasMayorRentabilidad = ideasMayorRentabilidad;
            this.ideasUsanDesarrolloSostenible = ideasUsanDesarrolloSostenible;
            this.ideasRentabilidadMayorPromedio = ideasRentabilidadMayorPromedio;
            this.ideasUsanTerritoriosOTransicion = ideasUsanTerritoriosOTransicion;
            this.ideaMayorDeptos = ideaMayorDeptos;
            this.ideaMayorTotalIngresos = ideaMayorTotalIngresos;
            this.ideaMayorInversionInfraestructura = ideaMayorInversionInfraestructura;                 
            this.sumaTotalInversiones = sumaTotalInversiones;
            this.sumaTotalIngresos = sumaTotalIngresos;
            this.totalIdeasUsanIA = totalIdeasUsanIA;
        }


    }


}

Controllers/IdeasDeNegocioController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using ProyectoAula4MVC.Models;
using ProyectoAula4MVC.Models.DB;
using ProyectoAula4MVC.Models.ViewModels;
using System.Net;
using System.Web.UI.WebControls;

namespace ProyectoAula4MVC.Controllers
{
    public class IdeasDeNegocioController : Controller
    {
        private IdeasDeNegocioDTO ideasDTO = new IdeasDeNegocioDTO();
        private ProyectoAula4MVC_DBEntities db = new ProyectoAula4MVC_DBEntities();

        // GET: Muestra lista global de ideas de negocio
        public ActionResult Index()
        {
            var ideas_De_Negocio = db.Ideas_De_Negocio.Include(i => i.Herramientas4RI).Include(i => i.Impactos);
            return View(ideas_De_Negocio.ToList());

        }

        //GET: formulario registrar idea
        [HttpGet]
        public ActionResult RegistrarIdea()
        {
            return View();
        }

        //POST: Registra y agrega idea a base de datos
        [HttpPost]
        public ActionResult RegistrarIdea(RegistroIdeaViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if (model.Departamentos.Count == 0)
                {
                    return View(model);
                }

                List<Departamentos> departamentos = new List<Departamentos>();
                foreach (var depto in model.Departamentos)
                {
                    Departamentos departamento = ideasDTO.buscarDepartamentoByNombre(depto.ToLower());
                    while (departamento == null)
                    {
                        departamento = ideasDTO.crearDepartamento(depto.ToLower());
                    }
                    departamentos.Add(departamento);
                }

                Impactos impacto = ideasDTO.buscarImpactoByNombre(model.Impacto.ToLower());
                while (impacto == null)
                {
                    impacto = ideasDTO.crearImpacto(model.Impacto.ToLower());
                }

                Herramientas4RI herramienta = ideasDTO.buscarHerramientaByNombre(model.Herramienta4RI.ToLower());
                while (herramienta == null)
                {
                    herramienta = ideasDTO.crearHerramienta(model.Herramienta4RI.ToLower());
                }

                Ideas_De_Negocio idea = ideasDTO.crearIdeaDeNegocio(model, impacto, herramienta);
                ideasDTO.crearDepartamentosIdea(departamentos, idea);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }

        }

        //GET: Muestra toda la informacion de una idea.
        [HttpGet]
        public ActionResult DetallesIdea(int? id)
        {

            Ideas_De_Negocio idea = ideasDTO.buscarIdeaById(id);
            if (idea == null)
            {
                return HttpNotFound();
            }

            List<Departamentos_Idea> deptosIdea = ideasDTO.buscarDepartamentosDeIdea(idea.ID_Idea);
            DetallesIdeaViewModel ideaConDeptos = new DetallesIdeaViewModel()
            {
                Idea = idea,
                Departamentos = deptosIdea,
            };
            return View(ideaConDeptos);
        }

        //GET: Muestra formulario para editar una idea.
        [HttpGet]
        public ActionResult EditarIdea(int Id)
        {

            Ideas_De_Negocio idea = ideasDTO.buscarIdeaById(Id);
            if (idea == null)
            {
                return HttpNotFound();
            }

            EditarIdeaViewModel model = new EditarIdeaViewModel();
            model.IdIdea = idea.ID_Idea;
            model.ValorInversion = idea.Valor_Inversion;
            model.TotalIngresos = idea.Total_Ingresos;
            model.Integrantes = new List<IntegranteViewModel>();


            return View(model);
        }

        //POST: Cambia los valores editados de la idea.
        [HttpPost]
        public ActionResult EditarIdea(EditarIdeaViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Ideas_De_Negocio idea = ideasDTO.buscarIdeaById(model.IdIdea);
            if (idea == null)
            {
                return HttpNotFound();
            }

            ideasDTO.editarIdea(model, idea);

            if (model.Integrantes.Count == 0)
            {
                return RedirectToAction("DetallesIdea", new { id = model.IdIdea });
            }

            foreach (var integrante in model.Integrantes)
            {
                ideasDTO.crearIntegrante(model.IdIdea, integrante);
            }

            return RedirectToAction("DetallesIdea", new { id = model.IdIdea });
        }

        [HttpGet]
        public ActionResult EliminarIntegrante(int idIntegrante) 
        {
            Integrantes integrante = ideasDTO.buscarIntegranteaById(idIntegrante);
            if (integrante == null)
            {
                return HttpNotFound();
            }

            ideasDTO.eliminarIntegrante(integrante);

            return RedirectToAction("DetallesIdea", new { id = integrante.ID_Idea });
        }
    }
}

Views/IdeasDeNegocio/DetallesIdea.cshtml
@model ProyectoAula4MVC.Models.ViewModels.DetallesIdeaViewModel
@{
    ViewBag.Title = "Detalles Idea de negocio";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    <body>

        <intput typeof="hidden" name="idIdea" value="@Model.Idea.ID_Idea">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Valor de inversion</th>
                        <th>Inversion en infraestructura</th>
                        <th>Igresos 3 años</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Html.DisplayFor(model => model.Idea.Nombre)</td>
                        <td>@Html.DisplayFor(model => model.Idea.Valor_Inversion)</td>
                        <td>@Html.DisplayFor(model => model.Idea.Valor_Inversion_Infraestructura)</td>
                        <td>@Html.DisplayFor(model => model.Idea.Total_Ingresos)</td>
                    </tr>
                </tbody>
            </table>
            <table class="table">
                <thead>
                    <tr>
                        <th>Impacto</th>
                        <th>Herramientas de la 4R.I</th>
                        <th>Departamentos</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Html.DisplayFor(model => model.Idea.Impactos.Nombre)</td>
                        <td>@Html.DisplayFor(model => model.Idea.Herramientas4RI.Nombre)</td>
                        <td>
                            <ul class="list-group">
                                @foreach (var depto in Model.Departamentos)
                                {
                                    <li>@depto.Departamentos.Nombre</li>
                                }
                            </ul>
                        </td>

                    </tr>
                </tbody>
            </table>
            <br>
            <h6>Integrantes</h6>
            <table class="table">
                <thead>
                    <tr>
                        <th>Identificacion</th>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Rol</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var integrante in Model.Idea.Integrantes)
                    {
                        <tr>

                            <td>@integrante.NumIdentificacion</td>
                            <td>@integrante.Nombre</td>
                            <td>@integrante.Apellidos</td>
                            <td>@integrante.Rol</td>
                            <td>@integrante.Email</td>
                            <td>@Html.ActionLink("Eliminar", "EliminarIntegrante", new { idIntegrante = integrante.ID_Integrante }, new { @class = "btn btn-danger" })</td>

                        </tr>
                    }

                </tbody>
            </table>

    </body>
}

Views/IdeasDeNegocio/EditarIdea.cshtml
@model ProyectoAula4MVC.Models.ViewModels.EditarIdeaViewModel
@{
    ViewBag.Title = "Editar Idea de negocio ";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("EditarIdea", "IdeasDeNegocio", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.IdIdea)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ValorInversion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-15">
                @Html.TextBoxFor(model => model.ValorInversion, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ValorInversion, "", new { @class = "text-danger" })
            </div>
        </div>
        <br>
        <div class="form-group">
            @Html.LabelFor(model => model.TotalIngresos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-15">
                @Html.TextBoxFor(model => model.TotalIngresos, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TotalIngresos, "", new { @class = "text-danger" })
            </div>
        </div>
        <br>
        @Html.LabelFor(model => model.Integrantes, htmlAttributes: new { @class = "control-label col-md-6" })
        <br>
        <div class="row">
            <div class="form-group">
                <table >
                    <tr>
                        <td>Identificacion</td>
                        <td>Nombre</td>
                        <td>Apellidos</td>
                        <td>Rol</td>
                        <td>Email</td>
                    </tr>
                    <tr>
                        <td><input class="form-control" type="number" id="NumIdI" /></td>
                        <td><input class="form-control" type="text" id="NombreI" /></td>
                        <td><input class="form-control" type="text" id="ApellidosI" /></td>
                        <td><input class="form-control" type="text" id="RolI" /></td>
                        <td><input class="form-control" type="text" id="EmailI" /></td>
                        <td><input class="btn btn-primary" value="Agregar" type="button" onclick="AgregarIntegrante(); return false;" /></td>
                    </tr>
                </table>
          
            </div>
            <div id="divIntegrantes">
                <table id="tablaIntegrantes" class="table">
                    <tr>
                        <td>Identificacion</td>
                        <td>Nombre</td>
                        <td>Apellidos</td>
                        <td>Rol</td>
                        <td>Email</td>
                        <td> </td>
                    </tr>
                    <tr>
                       
                    </tr>
                </table>
            </div>
        </div>
        <br>
        <div style="text-align:left">
            <input type="submit" class="btn btn-primary" value="Editar" />
        </div>
</div>


}

<script>
    var num = 0;
    function AgregarIntegrante() {
        //Guardar variable nombre ingresado
        let NumId = document.getElementById("NumIdI").value;
        let Nombre = document.getElementById("NombreI").value;
        let Apellidos = document.getElementById("ApellidosI").value;
        let Rol = document.getElementById("RolI").value;
        let Email = document.getElementById("EmailI").value;


        //Crear un renglon vacio para agregar
        //Mostrar el departmento registrado en la lista
        let Tabla = document.getElementById("tablaIntegrantes");
        let TR = document.createElement("tr");
        let TDNumId = document.createElement("td");
        let TDNombre = document.createElement("td");
        let TDApellidos = document.createElement("td");
        let TDRol = document.createElement("td");
        let TDEmail = document.createElement("td");
        TR.appendChild(TDNumId);
        TR.appendChild(TDNombre);
        TR.appendChild(TDApellidos);
        TR.appendChild(TDRol);
        TR.appendChild(TDEmail);
        TDNumId.innerHTML = NumId;
        TDNombre.innerHTML = Nombre;
        TDApellidos.innerHTML = Apellidos;
        TDRol.innerHTML = Rol;
        TDEmail.innerHTML = Email;
        Tabla.appendChild(TR);

        //Agregar departamentos a lista departamentos del modelo
        let DivIntegrantes = document.getElementById("divIntegrantes");
        let HiddenIndex = document.createElement("input");
        let HiddenNumId = document.createElement("input");
        let HiddenNombre = document.createElement("input");
        let HiddenApellidos = document.createElement("input");
        let HiddenRol = document.createElement("input");
        let HiddenEmail = document.createElement("input");
        HiddenIndex.name = "Integrantes.Index";
        HiddenIndex.value = num;
        HiddenIndex.type = "hidden";
        HiddenNumId.name = "Integrantes[" + num + "].NumId";
        HiddenNumId.value = NumId;
        HiddenNumId.type = "hidden";
        HiddenNombre.name = "Integrantes[" + num + "].Nombre";
        HiddenNombre.value = Nombre;
        HiddenNombre.type = "hidden";
        HiddenApellidos.name = "Integrantes[" + num + "].Apellidos";
        HiddenApellidos.value = Apellidos;
        HiddenApellidos.type = "hidden";
        HiddenRol.name = "Integrantes[" + num + "].Rol";
        HiddenRol.value = Rol;
        HiddenRol.type = "hidden";
        HiddenEmail.name = "Integrantes[" + num + "].Email";
        HiddenEmail.value = Email;
        HiddenEmail.type = "hidden";
        DivIntegrantes.appendChild(HiddenIndex);
        DivIntegrantes.appendChild(HiddenNumId);
        DivIntegrantes.appendChild(HiddenNombre);
        DivIntegrantes.appendChild(HiddenApellidos);
        DivIntegrantes.appendChild(HiddenRol);
        DivIntegrantes.appendChild(HiddenEmail);


        //Borrar el valor del input para agregar mas
        document.getElementById("NumIdI").value = "";
        document.getElementById("NombreI").value = "";
        document.getElementById("ApellidosI").value = "";
        document.getElementById("RolI").value = "";
        document.getElementById("EmailI").value = "";

        num++;

    }
</script>

Views/IdeasDeNegocio/Index.cshtml
@model IEnumerable<ProyectoAula4MVC.Models.DB.Ideas_De_Negocio>
    @{
        ViewBag.Title = "Ideas de negocio";
    }

    <h2>@ViewBag.Title</h2>

    <a class='btn btn-primary btn-sm' href='/IdeasDeNegocio/RegistrarIdea'>Registrar idea de negocio</a>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Impacto</th>
                <th>Valor inversion</th>
                <th>Inversion infraestructura</th>
                <th>Ingresos 3 años</th>
                <th>Herramientas 4RI</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Impactos.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Valor_Inversion)</td>
                    <td>@Html.DisplayFor(modelItem => item.Valor_Inversion_Infraestructura)</td>
                    <td>@Html.DisplayFor(modelItem => item.Total_Ingresos)</td>
                    <td>@Html.DisplayFor(modelItem => item.Herramientas4RI.Nombre)</td>
                    <td>
                        @Html.ActionLink("Editar", "EditarIdea", new { Id = item.ID_Idea }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Detalles", "DetallesIdea", new { Id = item.ID_Idea }, new { @class = "btn btn-primary" })

                    </td>

                </tr>
            }

        </tbody>
    </table>

Views/IdeasDeNegocio/RegistrarIdea.cshtml
@model ProyectoAula4MVC.Models.ViewModels.RegistroIdeaViewModel
@{
    ViewBag.Title = "Registrar Idea de negocio";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("RegistrarIdea", "IdeasDeNegocio", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-15">
            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>
    <br>
    <div class="form-group">
        @Html.LabelFor(model => model.Impacto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-15">
            @Html.TextBoxFor(model => model.Impacto, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Impacto, "", new { @class = "text-danger" })
        </div>
    </div>
    <br>
    <div class="form-group">
        @Html.LabelFor(model => model.ValorInversion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-15">
            @Html.TextBoxFor(model => model.ValorInversion, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ValorInversion, "", new { @class = "text-danger" })
        </div>
    </div>
    <br>
    <div class="form-group">
        @Html.LabelFor(model => model.ValorInversionInfraestructura, htmlAttributes: new { @class = "control-label col-md-10" })
        <div class="col-md-15">
            @Html.TextBoxFor(model => model.ValorInversionInfraestructura, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ValorInversionInfraestructura, "", new { @class = "text-danger" })
        </div>
    </div>
    <br>
    <div class="form-group">
        @Html.LabelFor(model => model.TotalIngresos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-15">
            @Html.TextBoxFor(model => model.TotalIngresos, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TotalIngresos, "", new { @class = "text-danger" })
        </div>
    </div>
    <br>
    <div class="form-group">
        @Html.LabelFor(model => model.Herramienta4RI, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-15">
            @Html.TextBoxFor(model => model.Herramienta4RI, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Herramienta4RI, "", new { @class = "text-danger" })
        </div>
    </div>
    <br>
    @Html.LabelFor(model => model.Departamentos, htmlAttributes: new { @class = "control-label col-md-6" })
    <br>
    <div class="row">
        <div id="divDepartamentos">
            <table id="tablaDepartamentos">
                
            </table>
            <input type="hidden" name="Departamentos.Index" id="Departamentos.Index">
        </div>
        <div class="form-group">
            Nombre
            <br>
            <input class="form-control" type="text" id="NombreDepartamento" />
            <input class="form-control" value="Agregar" type="button" onclick="AgregarDepartamento(); return false;" />
        </div>
    </div>
    <br>
    <div style="text-align:left">
        <input type="submit" class="btn btn-primary" value="Registrar" />
    </div>
</div>


}

<script>
    var num = 0;
    function AgregarDepartamento() {
        //Guardar variable nombre ingresado
        let Nombre = document.getElementById("NombreDepartamento").value;

        //Crear un renglon vacio para agregar
        //Mostrar el departmento registrado en la lista
        let Tabla = document.getElementById("tablaDepartamentos");
        let TR = document.createElement("tr");
        let TDNombre = document.createElement("td");
        TR.appendChild(TDNombre);
        TDNombre.innerHTML = Nombre;
        Tabla.appendChild(TR);

        //Agregar departamentos a lista departamentos del modelo
        let DivDepartamentos = document.getElementById("divDepartamentos");
        let HiddenIndex = document.createElement("input");
        let HiddenNombre = document.createElement("input");
        HiddenIndex.name = "Departamentos.Index";
        HiddenIndex.value = num;
        HiddenIndex.type = "hidden";
        HiddenNombre.name = "Departamentos[" + num + "]";
        HiddenNombre.value = Nombre;
        HiddenNombre.type = "hidden";
        DivDepartamentos.appendChild(HiddenIndex);
        DivDepartamentos.appendChild(HiddenNombre);
        

        //Borrar el valor del input para agregar mas
        document.getElementById("NombreDepartamento").value = "";

        num++;

    }
</script>